apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: michalkot.net
spec:
  secretName: 
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: michalkot.net
  dnsNames:
    - michalkot.net
    - www.michalkot.net